name: UN Environment

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  build:
    name: "Test and build app"
    if: contains(github.event.comment.body, 'rerun test') && github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x] # you have mentioned version 20.x which doesn't exist.

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: print body
        run: |
          echo "${{ github.event.comment.body }}" 
